# Generated by Django 5.2.11 on 2026-02-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Администратор"),
                    ("technologist", "Технолог"),
                    ("storekeeper", "Кладовщик"),
                    ("production_master", "Мастер участка"),
                    ("otk_senior", "Старший контролер ОТК"),
                ],
                default="production_worker",
                help_text="Выберите должность пользователя",
                max_length=20,
                verbose_name="Должность",
            ),
        ),
    ]
