# Generated by Django 5.2.11 on 2026-02-21 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blanks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Код склада"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Адрес/Расположение"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Склад",
                "verbose_name_plural": "Склады",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер документа"
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("receipt", "Поступление"),
                            ("transfer", "Перемещение"),
                            ("write_off", "Списание"),
                            ("sale", "Продажа"),
                        ],
                        max_length=20,
                        verbose_name="Тип движения",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Количество"
                    ),
                ),
                ("movement_date", models.DateTimeField(verbose_name="Дата движения")),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Основание"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="blanks.blank",
                        verbose_name="Заготовка",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "from_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements_from",
                        to="warehouse.warehouse",
                        verbose_name="Откуда",
                    ),
                ),
                (
                    "to_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements_to",
                        to="warehouse.warehouse",
                        verbose_name="Куда",
                    ),
                ),
            ],
            options={
                "verbose_name": "Движение заготовки",
                "verbose_name_plural": "Движения заготовок",
                "ordering": ["-movement_date"],
            },
        ),
        migrations.CreateModel(
            name="StockBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Количество",
                    ),
                ),
                (
                    "min_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Минимальный запас",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_balances",
                        to="blanks.blank",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balances",
                        to="warehouse.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Остаток на складе",
                "verbose_name_plural": "Остатки на складах",
                "unique_together": {("warehouse", "blank")},
            },
        ),
    ]
