# Generated by Django 5.2.11 on 2026-02-22 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0003_initial"),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="to_production_site",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите участок для прямой передачи",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="production.productionsite",
                verbose_name="Куда (участок)",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="from_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements_from",
                to="warehouse.warehouse",
                verbose_name="Откуда (склад)",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="to_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements_to",
                to="warehouse.warehouse",
                verbose_name="Куда (склад)",
            ),
        ),
    ]
