# Generated by Django 5.2.11 on 2026-02-23 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0005_remove_blankreceipt_accepted_by_and_more"),
        ("warehouse", "0002_stockmovement_to_production_site_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="receipt_request",
            field=models.ForeignKey(
                blank=True,
                help_text="Заявка, на основании которой создано движение",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="production.blankreceipt",
                verbose_name="Заявка на выдачу",
            ),
        ),
    ]
