# Generated by Django 5.2.11 on 2026-02-21 12:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlankReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер документа"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Количество"
                    ),
                ),
                (
                    "receipt_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата поступления",
                    ),
                ),
                (
                    "source_info",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Откуда поступило"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Поступление заготовок",
                "verbose_name_plural": "Поступления заготовок",
                "ordering": ["-receipt_date"],
            },
        ),
        migrations.CreateModel(
            name="ProductionSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Код участка"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Производственный участок",
                "verbose_name_plural": "Производственные участки",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="SiteBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Количество",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Остаток на участке",
                "verbose_name_plural": "Остатки на участках",
            },
        ),
        migrations.CreateModel(
            name="AssemblyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер отчета"
                    ),
                ),
                (
                    "report_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Дата отчета"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Собрано, шт")),
                (
                    "defect_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Брак, шт"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "produced_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assembly_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Собрал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчет о сборке",
                "verbose_name_plural": "Отчеты о сборке",
                "ordering": ["-report_date"],
            },
        ),
    ]
