# Generated by Django 5.2.11 on 2026-02-21 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blanks", "0001_initial"),
        ("production", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assemblyreport",
            name="product",
            field=models.ForeignKey(
                help_text="Какое изделие собиралось",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="products.product",
                verbose_name="Изделие",
            ),
        ),
        migrations.AddField(
            model_name="blankreceipt",
            name="accepted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_receipts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Принял",
            ),
        ),
        migrations.AddField(
            model_name="blankreceipt",
            name="blank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="blanks.blank",
                verbose_name="Заготовка",
            ),
        ),
    ]
