# Generated by Django 5.2.11 on 2026-02-21 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blanks", "0001_initial"),
        ("production", "0002_initial"),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionsite",
            name="warehouse",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="production_site",
                to="warehouse.warehouse",
                verbose_name="Привязанный склад",
            ),
        ),
        migrations.AddField(
            model_name="blankreceipt",
            name="production_site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipts",
                to="production.productionsite",
                verbose_name="Участок",
            ),
        ),
        migrations.AddField(
            model_name="assemblyreport",
            name="production_site",
            field=models.ForeignKey(
                help_text="На каком участке производилась сборка",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="production.productionsite",
                verbose_name="Участок",
            ),
        ),
        migrations.AddField(
            model_name="sitebalance",
            name="blank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="blanks.blank"
            ),
        ),
        migrations.AddField(
            model_name="sitebalance",
            name="production_site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="balances",
                to="production.productionsite",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sitebalance",
            unique_together={("production_site", "blank")},
        ),
    ]
