# Generated by Django 5.2.11 on 2026-02-22 05:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blankreceipt",
            options={
                "ordering": ["-receipt_date"],
                "verbose_name": "Заявка на выдачу заготовок",
                "verbose_name_plural": "Заявки на выдачу заготовок",
            },
        ),
        migrations.AlterField(
            model_name="blankreceipt",
            name="number",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Номер заявки"
            ),
        ),
        migrations.AlterField(
            model_name="blankreceipt",
            name="receipt_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата заявки"
            ),
        ),
    ]
