# Generated by Django 5.2.11 on 2026-02-23 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "production",
            "0004_alter_blankreceipt_options_alter_blankreceipt_number_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blankreceipt",
            name="accepted_by",
        ),
        migrations.AddField(
            model_name="blankreceipt",
            name="completed_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата выполнения"
            ),
        ),
        migrations.AddField(
            model_name="blankreceipt",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_receipts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создал",
            ),
        ),
        migrations.AddField(
            model_name="blankreceipt",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_receipts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Обработал",
            ),
        ),
        migrations.AddField(
            model_name="blankreceipt",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новая"),
                    ("processing", "В обработке"),
                    ("completed", "Выполнена"),
                    ("cancelled", "Отменена"),
                ],
                default="new",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="blankreceipt",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
