# Generated by Django 5.2.11 on 2026-02-23 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0005_remove_blankreceipt_accepted_by_and_more"),
        ("warehouse", "0003_stockmovement_receipt_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionsite",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="production_sites",
                to="warehouse.warehouse",
                verbose_name="Привязанный склад",
            ),
        ),
    ]
