# Generated by Django 5.2.11 on 2026-02-21 12:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blanks", "0001_initial"),
        ("production", "0002_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DefectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Наименование")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Вид брака",
                "verbose_name_plural": "Виды брака",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="DefectReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер акта"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Количество бракованных",
                    ),
                ),
                (
                    "report_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Дата акта"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание брака")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="defects/",
                        verbose_name="Фото брака",
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(default=False, verbose_name="Подтвержден"),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата подтверждения"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="blanks.blank",
                        verbose_name="Заготовка",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_defects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Подтвердил",
                    ),
                ),
                (
                    "detected_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detected_defects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обнаружил",
                    ),
                ),
                (
                    "production_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="defect_reports",
                        to="production.productionsite",
                        verbose_name="Участок",
                    ),
                ),
                (
                    "defect_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="quality_control.defecttype",
                        verbose_name="Вид брака",
                    ),
                ),
            ],
            options={
                "verbose_name": "Акт о браке",
                "verbose_name_plural": "Акты о браке",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="QualityStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название стандарта"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="quality/standards/",
                        verbose_name="Документ",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_standards",
                        to="products.product",
                        verbose_name="Изделие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стандарт качества",
                "verbose_name_plural": "Стандарты качества",
                "ordering": ["product", "name"],
            },
        ),
    ]
