# Generated by Django 5.2.11 on 2026-02-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality_control", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="defectreport",
            name="is_written_off",
            field=models.BooleanField(default=False, verbose_name="Заготовки списаны"),
        ),
    ]
