# Generated by Django 5.2.11 on 2026-02-21 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blanks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Категория изделий",
                "verbose_name_plural": "Категории изделий",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Артикул"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Наименование")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "drawing",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="products/drawings/",
                        verbose_name="Чертеж",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.productcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изделие",
                "verbose_name_plural": "Изделия",
                "ordering": ["article"],
            },
        ),
        migrations.CreateModel(
            name="ConsumptionNorm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Количество"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="used_in_products",
                        to="blanks.blank",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumption_norms",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Норма расхода",
                "verbose_name_plural": "Нормы расхода",
                "ordering": ["product", "blank"],
                "unique_together": {("product", "blank")},
            },
        ),
    ]
